### ISSUE TITLE
Problem loading on ubuntu 12.12

### ISSUE THREAD

**Issue by apux** [andys/qrscanner#2]
The gem is installed correctly, but when trying to run the rails server or console, I get this error

/home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require': /home/apux/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/site_ruby/1.9.1/x86_64-linux/qrscanner.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE - /home/apux/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/site_ruby/1.9.1/x86_64-linux/qrscanner.so (LoadError)
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in`block (2 levels) in require'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in`block in require'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in`require'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
    from /home/apux/lbs/Impressum/config/application.rb:9:in`<top (required)>'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@cbbfactura/gems/railties-3.2.11/lib/rails/commands.rb:39:in `require'
    from /home/apux/.rvm/gems/ruby-1.9.3-p362@cbbfactura/gems/railties-3.2.11/lib/rails/commands.rb:39:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

My ruby version is ruby 1.9.3p362 (2012-12-25 revision 38607) [x86_64-linux] through rvm
My rails version Rails 3.2.11
Any ideas about how to solve it?

**Comment by coin8086** [comment]
I have the same issue. My ruby version is 1.9.2. My OS is Ubuntu 12.04. The error is:

> 1.9.2-p320 :001 > require 'qrscanner'
> LoadError: /home/robert/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/i68
> 6-linux/qrscanner.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
> - /home/robert/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/i686-linux/
>   qrscanner.so
>      from /home/robert/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/r
>   ubygems/custom_require.rb:36:in `require'
>      from /home/robert/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/r
>   ubygems/custom_require.rb:36:in`require'
>      from (irb):1
>      from /home/robert/.rvm/rubies/ruby-1.9.2-p320/bin/irb:16:in `<main>'
